### ISSUE TITLE
`.clasp.json` not created if file exists in a parent directory

### ISSUE THREAD

**Issue by dustinmichels** [google/clasp#384] opened 2018-11-09 21:02 UTC
## Expected Behavior

```
clasp clone <scriptId>
```
generates a `.clasp.json` file, even I already have a file like this in a parent directory.

## Actual Behavior

If there is already a `.clasp.json` file in a parent directory, the file is not created by 

```
clasp clone <scriptId>
```

## Steps to Reproduce the Problem

1. Clone script into a folder and view contents. **Should see `.clasp.json`**
```bash
# clone script into repo
mkdir dummy-script
cd dummy-script
clasp clone 1hhHbd8iXq8fWdZAdL6zLU_93JhCFKRLFqSax5NByXJzWHN1m7WZaYjVi
ls -a
```

2. Move the script file into the parent repo, clear, clone again. **Should see no `.clasp.json`**

```bash
# clone script into repo
mv .clasp.json ..
rm -rf *
clasp clone 1hhHbd8iXq8fWdZAdL6zLU_93JhCFKRLFqSax5NByXJzWHN1m7WZaYjVi
ls -a
```

## Specifications

  - Node version (`node -v`): v8.11.4
  - Version (`clasp -v`): 1.6.3
  - OS (Mac/Linux/Windows): Windows 10, [cmder ](http://cmder.net/)([conEmu](https://conemu.github.io/)) console.

**Comment by takanakahiko** [comment] 2018-11-12 04:48
It using https://github.com/grant/dotf/ to edit `.clasp.json`.
I think it is a bug caused by https://github.com/grant/dotf/ .

**Comment by takanakahiko** [comment] 2018-11-12 05:31
I'm sorry, I made a mistake.
`find-parent-dir` checks if the dotfile exists in the parent directory.

https://github.com/google/clasp/blob/c1d1a6c5a679f47679d20b8dacf9cfad2d5834c9/src/dotfile.ts#L79

This is useful when you run the command in a subdirectory.

In this case, it seems that the current directory is recognized as a subdirectory of the project.

**Comment by dustinmichels** [comment] 2018-11-13 16:47
Gotcha. Is that an important use case? Running `clasp clone <scriptId>` in a sub-directory, and wanting to push that project to the parent directory? I don't really see why you would do that.

**Comment by takanakahiko** [comment] 2018-11-13 17:45
No, I think that clasp is not supposed to use that way.

For example of merit , you can run `clasp pull` , `clasp push` and more in anywhere of project directory.
`git` and `npm` also behave similarly this.
( I am sorry that my English is not good. )

**Comment by dustinmichels** [comment] 2019-01-17 19:05
Yes you're right, seems like reasonable behavior.

I was confused for a while why my projects were pushing the wrong repo, not realizing the `.clasp.json` wasn't created on `clasp clone` because it already existed (erroneously) in a parent directory.

A warning message might be helpful to others.

**Comment by grant** [comment] 2019-01-17 21:05
Did you try `clasp status`?

**Comment by grant** [comment] 2019-01-25 21:48
This seems like a side-effect, but not a big enough problem to be fixed since it's a user error.
Closing due to low priority.

**Closed by grant** 2019-01-25 21:48 UTC
