### ISSUE TITLE
getAllProjectFiles() ignore every file

### ISSUE THREAD

**Issue by connorhu** [google/clasp#809] opened 2020-09-16 13:37 UTC
There is a missing getApiFileType function call.
https://github.com/google/clasp/blob/377ead1312dc3e2c89729f2bb4b08a985dd877a5/src/files.ts#L85

**Comment by PopGoesTheWza** [comment] 2021-03-19 21:05
@connorhu can you please be more specific? I am unsure about both the issue and the fix here.

**Comment by sqrrrl** [comment] 2021-06-02 16:54
Closing due to lack of additional of information + lack of reproducibility.

**Closed by sqrrrl** 2021-06-02 16:54 UTC
