### ISSUE TITLE
Deploy failing with "Unable to deploy; Only one deployment can be created at a time" after few deployments

### ISSUE THREAD

**Issue by designgrill** [google/clasp#147] opened 2018-04-26 04:58 UTC
## Expected Behavior
On issuing command `clasp deploy <version>` the deployment should go if no other deployment is happening.

## Actual Behavior
Instead it fails with `Unable to deploy; Only one deployment can be created at a time` whereas I am able to deploy using the script editor.

## Steps to Reproduce the Problem
N/A

## Specifications

  - Node version v9.3.0
  - Version @google/clasp@1.1.5
  - OS Mac

**Comment by campionfellin** [comment] 2018-04-26 05:40
Hey @designgrill is there any other output when you run `clasp deploy`? Something like `Created version xx.` There is an error if you have more than 20 deployments. We are working on fixing that.

**Comment by designgrill** [comment] 2018-04-26 13:18
Hi @campionfellin, no I don't see anything like that.

And you are right, the issue first appeared with my 20th version.

```
$ clasp deploy 19
- A...VSns0s @19.
```

```
$ clasp deploy 20
Unable to deploy; Only one deployment can be created at a time
```

**Comment by campionfellin** [comment] 2018-04-26 13:37
I've made a PR: https://github.com/google/clasp/pull/149 to make that error message more clear. Please let me know if that issue appears again below version 20.

**Comment by designgrill** [comment] 2018-04-26 13:48
Thanks. Do you have workaround for this? I am not sure if I am using the versions and deployment right as I don't really need the old versions but they are still around.

**Comment by campionfellin** [comment] 2018-04-27 03:13
Hey @designgrill for now, you could try `clasp open` and then **File->Manage versions...** and then hit the **X** next to the old versions you want to remove.

**Comment by grant** [comment] 2018-05-04 15:28
Does `clasp undeploy` work? We should suggest that instead of just saying
`Unable to deploy; Only one deployment can be created at a time`

**Comment by campionfellin** [comment] 2018-05-05 00:05
I believe the message now is  from `ERROR.DEPLOYMENT_COUNT` : `Unable to deploy; Scripts may only have up to 20 versioned deployments at a time.`. Located here: https://github.com/google/clasp/blob/73765e073ed8571bc7bbd97dae400fffd3b477b3/src/utils.ts#L86

We can update that if needed.

**Comment by alx-andru** [comment] 2018-06-25 20:51
What is the intended workflow to create and deploy versions over time?

**Comment by grant** [comment] 2018-10-04 23:47
Are folks still experiencing this issue?

It looks like the API limits to 20 concurrent deployments of a script. (I think it used to be 1.)
This is like having 20 deployments of a website being hosted on the web. For most cases, it's not needed.

Please use
```
clasp deployments
# and
clasp undeploy <id>
```
to clean up your deployments.
---

If this is still happening, can you provide some steps to reproduce the problem?

**Comment by grant** [comment] 2018-10-29 22:59
I need more specific instructions to reproduce the issue. I think it may have been fixed since reported in April.
Closing.

**Closed by grant** 2018-10-29 22:59 UTC

**Comment by zffocussss** [comment] 2019-01-30 10:10
I have same issues.when using clasp deploy -d "xxx"

**Comment by dynamox-ac** [comment] 2022-01-21 17:23
> Are folks still experiencing this issue?
> 
> It looks like the API limits to 20 concurrent deployments of a script. (I think it used to be 1.) This is like having 20 deployments of a website being hosted on the web. For most cases, it's not needed.
> 
> Please use
> 
> ```
> clasp deployments
> # and
> clasp undeploy <id>
> ```
> 
> ## to clean up your deployments.
> If this is still happening, can you provide some steps to reproduce the problem?

That solves it for me. Thank you @grant!

**Comment by pradeep-gox** [comment] 2024-08-30 11:30
+1
