### ISSUE TITLE
Clasp push fails silently

### ISSUE THREAD

**Issue by paul-matthews** [google/clasp#255] opened 2018-07-06 17:56 UTC
`clasp push` fails with no error log:

## Expected Behavior
After clasp push, expect edits to be present in web interface.

## Actual Behavior
Clasp push produces following output:
`Push failed. Errors:`
No errors are displayed.

## Steps to Reproduce the Problem

  1. clasp clone <script ID>
  1. edit script file
  1. clasp push

## Specifications

  - Node version (`node -v`): v7.5.0
  - Version (`clasp -v`): 1.4.0
  - OS (Mac/Linux/Windows): Mac OS 10.13.3

**Comment by IanWhalen** [comment] 2018-07-06 18:33
@paul-matthews check to make sure you've enabled the apps script API?

https://script.google.com/home/usersettings

I hit the same issue less than 24 hours ago and that was the solution.

**Comment by paul-matthews** [comment] 2018-07-06 18:52
@IanWhalen solved, thank you.

Is there any chance this could be caught by the tool and reported?

**Comment by jtt48** [comment] 2018-07-18 15:22
I have the same error, sadly I already have the apps script API enabled, so that is not a solution for me.

**Comment by campionfellin** [comment] 2018-07-26 03:56
Hey @ikedaosushi , what does your `.claspignore` file look like?

**Comment by grant** [comment] 2018-07-26 18:59
Pushing many, many files could run into unknown issues (although it shouldn't.)
If you're able to target down which file is the problem, or if the problem is the number of files, that would help debug this issue.

**Comment by grant** [comment] 2018-07-30 23:43
@jtt48 @ikedaosushi Is this still an issue? Have you been able to ignore the files that you don't want to push?

**Comment by juncalpito** [comment] 2018-08-19 09:34
Still an issue for me. Same number of files as my last n pushes but for some reason it is no longer working. my ignore file is empty.

**Comment by Blacksmoke16** [comment] 2018-10-01 20:09
I'm experiencing the same issue.  Scripts API is on.

Node: 8.11.3
clasp: 1.6.0
OS: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

**Comment by grant** [comment] 2018-10-01 20:51
Can you provide examples of files that fail to push?

**Comment by Blacksmoke16** [comment] 2018-10-01 20:58
https://github.com/Blacksmoke16/GESI/tree/master/src/script Ones in this directory.

**Comment by grant** [comment] 2018-10-04 22:14
@Blacksmoke16 
I wan't able to reproduce the example you gave. This is my terminal output.

```
❤ clone git@github.com:Blacksmoke16/GESI.git
Cloning into 'GESI'...
Remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 721 (delta 46), reused 55 (delta 22), pack-reused 636
Receiving objects: 100% (721/721), 7.99 MiB | 7.74 MiB/s, done.
Resolving deltas: 100% (330/330), done.
❤ clasp create
? Give a script title: Script
Created new script: https://script.google.com/d/1paaxs093YlZ4j8J1-viEdhMuhkK776A3N9HsTb4sDiscIwoLI1DNthuN/edit
timmerman @ ⎇ (master) ~/Documents/trash/gesi/GESI/src/script
❤ clasp push
└─ appsscript.json
└─ endpoints.ts
└─ functions.ts
└─ gesi.ts
└─ pollyfill.ts
Pushed 5 files.
```

I did use the latest build of clasp (from GitHub), not sure if that makes a difference.

**Comment by Blacksmoke16** [comment] 2018-10-05 12:32
Yea i don't know what that was about.  I installed latest clasp, rm -rf'd the repo directory, recloned it, and it worked.

:man_shrugging:

**Comment by grant** [comment] 2018-10-09 00:05
I've spend a few minutes on this issue today. I can't really reproduce the discussion above:

## What if the API is not enabled?

We report this message if the API is disabled:

> User has not enabled the Apps Script API. Enable it by visiting https://script.google.com/home/usersettings then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

## What if the API returns an error?

If you have a syntax error, we report the error like this:

```
Push failed. Errors:
Syntax error: Missing ; before statement. line: 1 file: test
Files to push were:
└─ appsscript.json
└─ test.js
```

---

There's a lot of cases to test. The API reports errors in cases that pushing doesn't work. Also ignoring files may help.

I'm going to close this, but please report a new issue if you're still seeing something wrong.

**Closed by grant** 2018-10-09 00:05 UTC

**Comment by mageran** [comment] 2019-03-04 16:27
In my case, the reason for silent failure where backup files left behind by emacs (#somefile.js#). clasp status returned some useful message, which pointed me to that.

**Comment by ocramz** [comment] 2020-06-04 09:31
Just had the same problem as mageran, fixed by saving all Emacs buffers related to the clasp project.
