### ISSUE TITLE
clasp fails node_modules

### ISSUE THREAD

**Issue by 8888simon8888** [google/clasp#516] opened 2019-02-01 06:13 UTC
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
ignore node_modules when pushing to clasp

## Actual Behavior
uploads entire node_modules director and all sub folders and files

## Steps to Reproduce the Problem

1. I consulted the other node_modules issue regarding this (https://github.com/google/clasp/issues/67) and the steps suggested there did not work in my case. I am just testing clasp with a very simple setup: a Code.js file and an Index.html file. Clasp push and pull both work fine without having gulp installed and therefore no node_modules directory installed. As soon as I add gulp, the node_modules director appears and no matter what I try in the clasp ignore file the node_modules directory and all of its contents get pushed with clasp. 
2. my current .claspignore file is simply: 
```
**/**
!Code.js
!Index.htmls
!appsscript.json
```

3. I tried adding the following to my claspignore file to no avail: 
```
**/node_modules/**
node_modules/**
```

## Specifications

- Node version (`node -v`): v10.15.1
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Windows
``

**Comment by erickoledadevrel** [comment] 2019-02-01 16:24
This appears to be a duplicate of #67.

**Closed by erickoledadevrel** 2019-02-01 16:24 UTC
