### ISSUE TITLE
Avoiding Ctrl+c exits to every call

### ISSUE THREAD

**Issue by topherbuckley** [google/clasp#805] opened 2020-09-01 08:16 UTC
## Expected Behavior
Running any call (e.g. `clasp push`) should push to the server, then exit, returning to the normal terminal prompt.

## Actual Behavior
Running any call (e.g. `clasp push`)  pushes correctly to the server, but the terminal remains unresolved, or unclosed properly. It is responsive, but will not return to the normal terminal prompt without forcefully exiting with Ctrl+c. 

## Steps to Reproduce the Problem

1. `clasp push`
1. Hangs until Ctrl-c input

## Specifications

- Node version (`node -v`): 14.9.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Linux Ubuntu 18.04.4

**Comment by imthenachoman** [comment] 2021-01-29 02:46
There seem to be multiple issues for the same thing. I am sure there are more but I can't find all of them. Not sure which one we want to be primary so I am posting this in all of them. Any resolution or idea what is wrong?

- https://github.com/google/clasp/issues/805 (this one)
- https://github.com/google/clasp/issues/717
- https://github.com/google/clasp/issues/257

**Comment by topherbuckley** [comment] 2021-02-03 03:50
Sorry, I hanve't touched this since I posted back in Sept 2020 with no plans to return to this as Apps Script was too buggy for my purposes.

**Comment by imthenachoman** [comment] 2021-02-03 04:37
I hear ya. I love how much you can do with it but it has so many one off issues that prevent it from being a full fledged solution platform. I wish Google invested more time/resources on it. Either way, I just wanted to let the devs of `clasp` know there are numerous other folks raising this particular issue.

**Comment by PopGoesTheWza** [comment] 2021-02-19 10:07
Out of curiosity, do the issue also occurs when using `npm install -g forked-clasp` instead of `npm install -g @google/clasp`?

forked-clasp is an npm package built from https://github.com/PopGoesTheWza/clasp/tree/forked which includes many changes/fixes and was heavily refactored.

**Comment by imthenachoman** [comment] 2021-02-20 02:46
Do I need to uninstall @google/clasp first?

**Comment by PopGoesTheWza** [comment] 2021-03-07 09:56
@imthenachoman yes. Uninstall google/clasp globally before installing forked-clasp

**Comment by imthenachoman** [comment] 2021-03-15 17:15
`forked-clasp` still has the same issue.

It pushes the files and then sits for 30+ seconds.

```
% time clasp push
└─ appsscript.json
└─ code.js
Pushed 2 files.
clasp push  1.23s user 0.26s system 5% cpu 27.725 total
```

**Comment by PopGoesTheWza** [comment] 2021-03-15 17:30
@imthenachoman but it exits normally after the "sitting" time, right?

**Comment by imthenachoman** [comment] 2021-03-15 17:53
Yes -- but that is the same experience with normal clasp. The clasp calls do their thing and then just sit. Been trying to find out why that is and how to fix it.

**Comment by PopGoesTheWza** [comment] 2021-03-15 17:58
Without a windows system to test, it is difficult for me to find why it "hangs" for a while before exiting

**Comment by imthenachoman** [comment] 2021-03-15 18:02
It happens on my MacOS system too. It's happening on both Windows and MacOS for me.

**Comment by nilp0inter** [comment] 2021-03-16 15:09
I am experiencing the same issue on Linux (using nixpkgs stable version: v2.2.1).  It seems to affect only to subcommands that actually make calls to the server.

**Comment by PopGoesTheWza** [comment] 2021-03-16 18:45
My guess is that there are some unresolved promises/async functions which keeps the application from returning immediately. During previous refactoring I did focus on such issues, but obviously there is still some loose ends.

**Comment by imthenachoman** [comment] 2021-03-16 18:53
I have not looked through `clasp` code as it is out of my depth but is there any debug flag we can use to get more verbose output? What I'm trying to figure out is exactly what function/call/line the code is "hanging" on.

**Comment by PopGoesTheWza** [comment] 2021-03-16 19:05
We can try adding https://www.npmjs.com/package/why-is-node-still-running or https://www.npmjs.com/package/why-is-node-running on my fork so that I can release a version with information about what is delaying the exit.

**Comment by nilp0inter** [comment] 2021-03-16 19:26
> We can try adding https://www.npmjs.com/package/why-is-node-still-running or https://www.npmjs.com/package/why-is-node-running on my fork so that I can release a version with information about what is delaying the exit.

Sounds like a plan! I volunteer to test it out.

**Comment by PopGoesTheWza** [comment] 2021-03-16 20:48
@imthenachoman @nilp0inter you can try https://www.npmjs.com/package/forked-clasp/v/2.8.0

it has the option `-W` or `--why` which will log what is still running upon exit.

i.e. `clasp version --why`

**Comment by nilp0inter** [comment] 2021-03-17 19:37
@PopGoesTheWza Here is the log of running `clasp list --why` on my machine: https://gist.github.com/nilp0inter/13f29a38fd8ec0d569081ef23e5cf4a3

The behavior is the same.  The command runs and produces all the output you see in the log in about 2 seconds, then it sits still for about 70 seconds, then it exits.

I hope this helps.  Please, let me know if you require further tests.

**Comment by PopGoesTheWza** [comment] 2021-03-17 20:04
@nilp0inter Your output is nearly identical to mine... (macos big sur, immediate exit)

**Comment by PopGoesTheWza** [comment] 2021-03-17 20:31
@nilp0inter Can you try forked-clasp 2.8.1? There is now a new option `-X` `--force-exit` which explicitly invoke `process.exit()`

**Comment by nilp0inter** [comment] 2021-03-17 20:39
I executed `clasp list -X`, the process exited too early not producing any output.

I executed again adding `--why` resulting in this output: https://gist.github.com/nilp0inter/2ce26a50e2fd3c706724b9be130d6505

**Comment by imthenachoman** [comment] 2021-03-18 02:48
@PopGoesTheWza Are you saying you don't see the delay on your system? I'm seeing it on every system I have.

**Comment by PopGoesTheWza** [comment] 2021-03-18 04:53
I never experienced any significant, noticeable delay. Maybe up to 2 seconds on some rare occasions. Typically I'm using LTS node (i.e. 14.x atm) from bash/zsh on latest macOS.

**Comment by PopGoesTheWza** [comment] 2021-03-18 08:22
I was able to test `login` and `list` commands on a Windows 2019 server... no delai before clasp exits.

**Comment by nilp0inter** [comment] 2021-03-18 08:28
May this be a configuration issue in our end (or Google's end) instead of a bug?

**Comment by imthenachoman** [comment] 2021-03-18 11:38
Is there a way to make a trimmed down version of clasp push or some command to see if it does the same thing? I don’t know NodeJS or what clasp code does to try to create it.

**Comment by nilp0inter** [comment] 2021-03-18 17:15
This change fixed the issue for me https://github.com/google/clasp/pull/828

**Comment by PopGoesTheWza** [comment] 2021-03-18 19:37
@nilp0inter @imthenachoman please give a try to this release https://github.com/PopGoesTheWza/clasp/releases/tag/2.8.2

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
clasp --version
```

Then add the `-X` option if you want to force exit:

```shell
clasp list -X
```

P.S.: I tried MacOS Catalina & Big Sur as well as Windows Server 2019 without experiencing this issue.

**Comment by nilp0inter** [comment] 2021-03-18 20:47
@PopGoesTheWza, now it works.

Are you considering adding this -X flag to the command? If you are, I suggest using an environment variable instead so the users don't have to change every single automation they have already in place.

**Comment by PopGoesTheWza** [comment] 2021-03-18 21:07
@nilp0inter the  `-X` / `--force-exit` will likely stay until we identify the root cause for this issue.

`forked-clasp` already has a few environment variables (https://github.com/PopGoesTheWza/clasp/blob/forked/docs/config-files.md#environment-variables) but they are oriented towards handling configuration files.

I have considered also having a `force-exit` property in `clasp.json`... but until we have a root cause and know what we are fixing, I am reluctant to shoehorn this in the current code.

More people can express their opinion on this?

**Comment by imthenachoman** [comment] 2021-03-18 22:10
As a developer I do not like/support band-aid solutions. I wish I knew Node.JS cause then I could try to help debug. If I could, the first thing I would do is create a minimized version of a `clasp` command -- a single script that does what `clasp ...` does. If this minimized version has the same issue then it'll be easier to debug.

**Comment by imthenachoman** [comment] 2021-03-18 22:11
Is there a way to see the call trace/log/dump for a clasp command? Maybe I could use that to create a minimized version?

**Comment by PopGoesTheWza** [comment] 2021-03-18 22:19
@imthenachoman since I failed to reproduce the issue on 3 distinct systems, I am unsure the issue is clasp itself

I just released `forked-clasp` 2.9.0 which may have more useful information from the `-W`/`--why` option

Does the issue occurs with every commands?

[ ] `clasp --version`
[ ] `clasp login --status`
[ ] `clasp list`
etc.

**Comment by imthenachoman** [comment] 2021-03-19 00:29
> I am unsure the issue is clasp itself

I agree. But it’s a hard thing to debug. That’s why I’m trying to get a minimized version. 

> Does the issue occurs with every commands?

I will check.

Out of curiosity, what kind of Google account do you have? I’m having the issue on both Enterprise and personal/free. 

I’m trying to get a local build environment for clasp. If I can get it running I will try to do some debugging. I’ll just throw output to STDOUT to see if I can figure it out.

**Comment by nilp0inter** [comment] 2021-03-19 00:39
@PopGoesTheWza, Here are the results of executing `forked-clasp` 2.9.0:

I marked the commands where the issue appears:

- [X] `clasp login --status`
- [X] `clasp pull`
- [X] `clasp push`
- [X] `clasp status`
- [X] `clasp deployments`
- [X] `clasp deploy`
- [X] `clasp undeploy`
- [X] `clasp versions`
- [X] `clasp list`
- [ ] `clasp help`
- [ ] `clasp paths`
- [X] `clasp create`

Here you have the [output log](https://gist.github.com/nilp0inter/bafb6c99cf8546af49ac7a2908c2be61) for each of the commands run. I executed them using [this script](https://gist.github.com/nilp0inter/67e29fb3ad4c923827696677daeabff8), as you can see I run them using `time` and passing `--why` in a first run and `--why -X` in a second run.

For the rest of the commands I run them manually (given that they require some input or are somewhat harder to script).  This is the result:

- [X] `clasp clone`
- [ ] `clasp open`
- [X] `clasp run`
- [ ] `clasp settings`
- [ ] `clasp logout`
- [X] `clasp login` 

I can provide you access to a system where the issue can be reproduced.  In fact I cannot not reproduce it (:

**Comment by imthenachoman** [comment] 2021-03-19 02:18
@PopGoesTheWza You are in France, right? I wonder if this is a geographic issue? Or maybe something linked to your account? Do you have another Google account you can try with to see if you do or don't get the issue?

I have tried a few different accounts and all of them have it.

**Comment by PopGoesTheWza** [comment] 2021-03-19 08:26
@imthenachoman @nilp0inter I am wondering if the node version, and how it was install could relate why the issue.

On MacOS, my node is always installed using `nvm`.

```shell
nvm install 14.16.0
nvm use 14.16.0
```

On Windows Server 2019, nodee is installed manually:

- unzip `node-v14.15.4-win-x64.zip` to `C:\SomeFolder\node-v14.15.4-win-x64`
- declare the system environment variable `NODE_PATH` to `C:\SomeFolder\node-v14.15.4-win-x64`
- add `%NODE_PATH%` to the system environment variable `PATH`
- open a new `cmd.exe`command prompt to take the environment variable into account

I also keep global packages to thee bare minimum.

```shell
node --version
npm install -g npm forked-clasp
npm list -g --depth=0
``` 

I don't remember needing to `sudo` or `run as administrator` to install or use node (though on windows things can easilly get trickier)

**Comment by PopGoesTheWza** [comment] 2021-03-19 08:34
> I agree. But it’s a hard thing to debug. That’s why I’m trying to get a minimized version.

`clasp` basic commands like `help`, `paths` and `settings` do not seem to trigger the delay. Those typically have little if any network interaction. Could some network setting/software/device be in cause? (I use clasp with and without  corporate vpn, and corporate anti-virus is running on all the systems I tested)

> Out of curiosity, what kind of Google account do you have? I’m having the issue on both Enterprise and personal/free.

I use a couple of free Google accounts.

**Comment by nilp0inter** [comment] 2021-03-19 08:57
@PopGoesTheWza a bit more info about my setup:

OS: Arch Linux
```console
$ node --version
v15.12.0
$ npm list -g --depth=0
/usr/lib
├── firebase-tools@7.8.1
├── forked-clasp@2.9.0
├── gherkin-lint@3.3.6
├── graphql-cli@2.16.7
├── graphqlviz@2.1.0
├── graphqurl@0.3.2
├── node-gyp@7.1.2
├── npm@7.6.3
├── semver@7.3.4
├── typescript@4.2.3
└── uglify@0.1.5
```

My node version is installed via the standard Arch method, using `pacman -S`.

I'll try to reproduce the issue in a clean docker container today.

**Comment by nilp0inter** [comment] 2021-03-19 09:06
> Looking at @nilp0inter results, the package `dns-socket` stands out. ...

@imthenachoman , @PopGoesTheWza  Yes, that's it!! I am able now to reproduce/non-reproduce the issue at will.

My network has a firewall restriction to disallow connections to extraneous DNS servers.  So no UDP/TCP connection can be made from my network to the internet.

When I disable the firewall rule `clasp` the issue disappears.

So it looks that some part of the code is performing a DNS query with its own custom server address.

**Comment by PopGoesTheWza** [comment] 2021-03-19 09:29
@nilp0inter out of curiosity, can you reproduce the issue using only https://github.com/sindresorhus/is-online-cli

I have little time available until after the weekend, so whatever information @imthenachoman and you can put together on:

- confirming firewall as the root cause
- identify best approach to solve or workaround it

will be much appreciated.

**Comment by PopGoesTheWza** [comment] 2021-03-19 09:48
@imthenachoman @nilp0inter please have a look at this issue. It looks like related https://github.com/sindresorhus/public-ip/issues/15

**Comment by nilp0inter** [comment] 2021-03-19 10:12
@PopGoesTheWza I cannot reproduce the issue using `is-online`.  This is the result of running it on my machine:

```console
> $ time is-online
✔ Online
is-online  0.17s user 0.02s system 88% cpu 0.215 total
```

To **confirm the DNS connections as the root cause** I sniffed the network with and without the firewall rule in place.
My network is `10.4.1.0/24`, my laptop is `10.4.1.105` and my local DNS server is `10.4.1.1`.

This is the network capture WITHOUT the DNS block rule:
![image](https://user-images.githubusercontent.com/1224006/111763552-93c25c80-88a2-11eb-90b2-95ce8b7caed5.png)

This is the network capture WITH the DNS block rule:
![image](https://user-images.githubusercontent.com/1224006/111763593-9f158800-88a2-11eb-84aa-7ea883e57150.png)

As you can see, around time ~0.198, `clasp` initiates a DNS query agains OpenDNS servers `208.67.222.222` which in the case of the disabled firewall rule resolves, but, with the DNS blockage it doesn't and keeps retrying till time ~75.

Given the domain `clasp` (or one of its components, probably `public-ip@4.0.3`) is trying resolve **myip.opendns.com** I guess is trying to get what my public WAN ip is.  What is the purpose of that query I don't really know...

I'll try to identify the part of the code that is making the query so that we can know why so we can **identify best approach to solve or workaround it**.

**Comment by nilp0inter** [comment] 2021-03-19 10:54
@PopGoesTheWza To further confirm that `public-ip`/`is-online` is causing the issue I removed the call to `isOnline()` in here:

https://github.com/google/clasp/blob/4464f73465dd9697ae22fab81c42370ca98232c6/src/utils.ts#L172

and replaced it with `true`.  The issue disappeared immediately.

In the documentation https://github.com/sindresorhus/is-online#how-it-works they mention that `is-online` tries to determine if the machine is connected to the internet by performing several checks in parallel and it returns `true` when the first of them returns `true`.

My guess is that the one performed via `captive.apple.com` is working on my network (given that it uses the proper local DNS) and the others (OpenDNS and myaddr.google.com) are not.  The promise `isOnline()` returns, making `clasp` progress, but the remaining inner promises are not cancelled and keep dangling until the number of retries/timeout occurs 60/70 seconds later.

**Comment by imthenachoman** [comment] 2021-03-19 12:56
Is there a forked version I can try to install? I can't seem to get it to compile on my machine (some Node error that I can't figure out). I also can't compile from source on work machine. If there is a forked version I can try that.

**Comment by PopGoesTheWza** [comment] 2021-03-19 14:30
> Is there a forked version I can try to install?

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```

You should get version 2.9.0 with `-W` and `-X` options.

I'll try to put up a release which address the `is-online` package issue asap.

**Comment by PopGoesTheWza** [comment] 2021-03-19 17:33
@imthenachoman @nilp0inter maybe switching to `is-reachable` with specific addresses is a better option? https://github.com/sindresorhus/is-online/issues/61#issuecomment-537118653

**Comment by nilp0inter** [comment] 2021-03-19 17:48
@PopGoesTheWza,

Personally I think that the whole concept of trying to detect if there is an Internet connection is not very sound.
There is always going to be an scenario in which the check can fail or report the wrong information.
Even if the check success, the connection can be dropped after the test and before the actual operation.  There is an inherent race condition.

Given that it's easier to ask forgiveness than it is to get permission.  Why don't remove the connectivity check all together and manage connection errors when the actions fail due to connection errors?

**Comment by PopGoesTheWza** [comment] 2021-03-19 18:37
@imthenachoman @nilp0inter most if not all online operations rely on `www.googleapis.com`, `script.google.com`, `console.developers.google.com`, `console.cloud.google.com` and `drive.google.com`

So dropping `is-online` for `is-reachable` while checking the above set of addresses, while maybe not perfect, could be a reasonable alternative?

Should @grant or @takanakahiko be available, I'd like to know their position on this.

**Comment by PopGoesTheWza** [comment] 2021-03-19 18:58
@imthenachoman @nilp0inter I released forked-clasp 2.10.0 on npm: https://github.com/PopGoesTheWza/clasp/releases/tag/2.10.0

Please give it a try.

**Comment by nilp0inter** [comment] 2021-03-19 19:06
@PopGoesTheWza is not working for me:

```console
$ clasp list
Error: Looks like you are offline.
$ clasp login --status
You are logged in as an unknown user.
```

**Comment by PopGoesTheWza** [comment] 2021-03-19 19:23
Fixed in https://github.com/PopGoesTheWza/clasp/releases/tag/2.10.1

**Comment by nilp0inter** [comment] 2021-03-19 19:31
It appears to work now

**Comment by PopGoesTheWza** [comment] 2021-03-19 19:33
@nilp0inter like? No more issue? No delayed exit? No need for `-X`? Not feeling grateful for fix? ;)

**Comment by nilp0inter** [comment] 2021-03-19 19:38
Sorry, I didn't want to sound ungrateful.  Thank you very much for your hard work.

It is just I didn't think that the issue was closed, I mean, I thought you'll want to perform some more tests, maybe via @imthenachoman.

 Did I hurt your feelings or something?

**Comment by PopGoesTheWza** [comment] 2021-03-19 19:45
Just teasing.

Since this issue has been floating for quite a while, I will not rush to close it until some time to confirm it is fine now.

I am barely using clasp now and with TravisCI being broken, testing is minimal. In the last few days, I also bumped a few dependencies but without checking if it didn't break anything.

If all goes well I'll drop `-X` from next release (`-W`may still be useful in the future.)

**Comment by nilp0inter** [comment] 2021-03-19 19:55
You scared me, @PopGoesTheWza! 🤣🤣🤣

Just to be clear, I am a little bit concern about the fix.  As I said, I think the solution is brittle and will break for somebody else in the future.  You have all the right to ignore my opinion, but please, consider adding an environment variable to disable the check.

Again, thank you very much for all your effort ❤️ ✨✨🍰✨✨

**Comment by PopGoesTheWza** [comment] 2021-03-19 20:10
Removing all kind of is-online testing would go against the philosophy of original Google designers. Thus I will not rush taking such a route.

**Comment by imthenachoman** [comment] 2021-03-20 20:21
What was decided on the DNS? I don't see why `clasp` should/would use its own DNS. It should respect the network's DNS settings for various security related reasons.

I tested just `clasp` with `forked-clasp` on my home machine/network. I will check on work/corporate machine/network on Monday.

**Comment by PopGoesTheWza** [comment] 2021-03-21 08:18
@imthenachoman in a nutshell:

`@google/clasp` use the `is-online` package to check if online connection is available. This package tests against OpenDns (among other addresses) which may be blocked by a firewall rule (local or network.)

When blocked it can cause some unresolved promises/async operations, which translate into a clasp command taking a long time upon exit.

To address this situation, we considered some options:

- Eliminate any test about having an online access. I vetoed against such approach because it goes against initial design choices for Google authors of `@google/clasp`
- Fix/workaround `is-online` usage, possibly opening an issue in this package repo. A sound approach, though I have little time and energy to do it myself.
- Switch to `is-reachable` package and effectively testing connection to half a dozen 'well-known' addresses used by clasp.

The last option seems like a reasonable tradeoff, easy to implement. Latest `forked-clasp` npm release has it.

**Comment by imthenachoman** [comment] 2021-03-21 13:29
Why not just check it against the API endpoint used to update GAS code? Even if it can access google.com but can't access the API endpoints then it is no good. I could see a corporate FW block the API endpoint but not google.com.

**Comment by PopGoesTheWza** [comment] 2021-03-21 13:49
https://github.com/PopGoesTheWza/clasp/blob/4e6a832d7ee5954182cb2dfd3b91cea4106aad9e/src/utils.ts#L207-L213

**Comment by imthenachoman** [comment] 2021-03-21 14:16
I like this solution. I vote yes for what @PopGoesTheWza has done.

**Comment by imthenachoman** [comment] 2021-03-21 14:23
I just tested this on corporate network and it works now. Brilliant! Thank you!

**Comment by nilp0inter** [comment] 2021-03-24 23:07
@PopGoesTheWza , I've been using the patched version daily and I am getting the `Error: Looks like you are offline.` intermitently. Sometimes I cannot use the application for several minutes in a row which is pretty annoying.

I've been unable to identify a pattern so far.  Any ideas?

**Comment by PopGoesTheWza** [comment] 2021-03-25 08:08
@nilp0inter Do you think that a build which would display which tested URL is "unreachable" would help?

**Comment by nilp0inter** [comment] 2021-03-25 08:24
> @nilp0inter Do you think that a build which would display which tested URL is "unreachable" would help?

Yes, I think so.

**Comment by PopGoesTheWza** [comment] 2021-03-25 08:46
@nilp0inter try `forked-clasp` 2.11.1

**Comment by nilp0inter** [comment] 2021-03-25 09:35
I am getting this results with `forked-clasp` 2.11.1:

```console
nil@xan ~                                                                                                           [10:32:32]
> $ clasp list
script.google.com ✖
console.developers.google.com ✖
console.cloud.google.com ✖
drive.google.com ✖
Error: Looks like you are offline.

nil@xan ~                                                                                                           [10:33:04]
> $ clasp login --status
script.google.com ✖
console.developers.google.com ✖
console.cloud.google.com ✖
drive.google.com ✖
You are logged in as an unknown user.
```

Looks like now everything is detected as down?  Nevertheless I am able to access all domains from the browser, and the old version of clasp works (with the DNS drop rule, of course)

**Comment by PopGoesTheWza** [comment] 2021-03-25 10:24
@nilp0inter I edited my copy of the code to also display successes and tested:

```shell
~/ref/clasp forked
❯ node ./build/src/index.js login --status
script.google.com ✔
console.developers.google.com ✔
console.cloud.google.com ✔
drive.google.com ✔
script.google.com ✔
console.developers.google.com ✔
console.cloud.google.com ✔
drive.google.com ✔
You are logged in as popgoesthewza@gmail.com.
```

What can possibly cause issues on your side?

**Comment by nilp0inter** [comment] 2021-03-25 11:04
I have an slow Internet connection. I executed it now and get no error:

```console
> $ clasp login --status                                                                                          [±master ●●]
You are logged in as xxxxxx@gmail.com.
```

**Comment by PopGoesTheWza** [comment] 2021-03-25 11:06
@nilp0inter We could try with a longer timeout? https://github.com/sindresorhus/is-reachable#options

**Comment by nilp0inter** [comment] 2021-03-25 11:16
I don't know... the command without the Internet check, usually finish in less than 5 seconds.  Maybe 5 seconds?

**Comment by PopGoesTheWza** [comment] 2021-03-25 11:27
@nilp0inter try `forked-clasp` version 2.11.2. I set timeout to 10000 ms.

**Comment by PopGoesTheWza** [comment] 2021-03-25 18:35
@imthenachoman have you also experienced issues like the one @nilp0inter reported?

**Comment by imthenachoman** [comment] 2021-03-26 02:27
I have not. But let me check with others at my company.

**Comment by nilp0inter** [comment] 2021-03-30 09:56
@PopGoesTheWza , sorry I've been very busy at work and I was unable to perform any testing.

I am now testing version `2.11.2` with increased timeout.  And I am getting this results:

```console
nil@xan ~/Project/SePScripts                                                        [11:45:14]
> $ clasp status                                                                  [±master ●●]
console.cloud.google.com ✖
Error: Looks like you are offline.

nil@xan ~/Project/SePScripts                                                        [11:45:42]
> $ clasp login --status                                                          [±master ●●]
script.google.com ✖
console.developers.google.com ✖
console.cloud.google.com ✖
drive.google.com ✖
You are logged in as an unknown user.

nil@xan ~/Project/SePScripts                                                        [11:46:00]
> $ clasp status                                                                  [±master ●●]
script.google.com ✖
console.developers.google.com ✖
console.cloud.google.com ✖
drive.google.com ✖
Error: Looks like you are offline.

nil@xan ~/Project/SePScripts                                                        [11:46:19]
> $ clasp -v                                                                      [±master ●●]
2.11.2

nil@xan ~/Project/SePScripts                                                        [11:51:52]
> $ clasp login --status                                                          [±master ●●]
script.google.com ✖
You are logged in as an unknown user.

nil@xan ~/Project/SePScripts                                                        [11:52:09]
> $ clasp login --status                                                          [±master ●●]
You are logged in as xxxxxxxx@gmail.com.


```

As you can see, it is pretty erratic, it seems to work every few tries and when it fails the errors are different.  I am not sure this is related to timeouts anymore.  In case you are wondering I have no proxies or any other restriction in my Internet access now.

Thank you!

**Comment by PopGoesTheWza** [comment] 2021-05-12 22:20
Fixed in https://github.com/google/clasp/releases/tag/v2.3.1

**Closed by PopGoesTheWza** 2021-05-12 22:20 UTC
