### ISSUE TITLE
clasp list shows nothing

### ISSUE THREAD

**Issue by yang** [google/clasp#574] opened 2019-03-13 22:02 UTC
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
`clasp list` lists scripts.

## Actual Behavior
```
$ clasp login
Logging in globally...
🔑 Authorize clasp by visiting this url:
XXX

Authorization successful.

Default credentials saved to: ~/.clasprc.json (/Users/yang/.clasprc.json).

$ clasp create
? Clone which script? sheets
Created new Google Sheet: https://drive.google.com/open?id=1--S7EGbMWszRi3xWCkqjmOXat3lbm__72qT_noY1Gz8
Created new Google Sheets Add-on script: https://script.google.com/d/1Hkc8JcOSXfNy_9eYsRtHu4gv3y0BWBGyJD9498pMaYNL_nZWlvgu6mkY/edit
Cloned 1 file.
└─ appsscript.json

$ clasp push
└─ appsscript.json
Pushed 1 file.

$ clasp list
No script files found.
```

## Steps to Reproduce the Problem

1. See above

## Specifications

- Node version (`node -v`): 10.15.1
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment] 2019-03-20 23:18
Are you sure you're logged in to the right account?

Can you create a script, then list again?

**Comment by yang** [comment] 2019-03-21 00:44
Yeah, the script was created also by clasp just a few lines above the list command.

**Comment by takanakahiko** [comment] 2019-03-22 16:22
`clasp list` is command or listing your `standalone` script projects (no include `sheet` script projects).

**Comment by grant** [comment] 2019-03-22 16:27
@takanakahiko is right. So, we can only show `standalone` scripts. This example is a sheets add-on.

Bound scripts aren't visible by the Drive API:
https://developers.google.com/apps-script/guides/bound

Marking as API support needed.

**Comment by tehhowch** [comment] 2019-03-24 04:39
Seems like a closable duplicate of https://github.com/google/clasp/issues/208

**Comment by grant** [comment] 2019-03-24 04:43
Yes, a duplicate.

**Closed by grant** 2019-03-24 04:43 UTC
Labels: API support needed
