### ISSUE TITLE
Clasp commands execute but never return to the prompt

### ISSUE THREAD

**Issue by swvajanyatek** [google/clasp#717] opened 2019-11-20 16:47 UTC
## Expected Behavior
clasp commands, such as "clasp status", should execute and return to the command prompt

## Actual Behavior
clasp commands execute, but seem to hang indefinitely after executing, requiring a crtrl+c to get back to the command prompt

## Steps to Reproduce the Problem
1.  clasp login
2. execute any command 

## Specifications

- Node version (`node -v`):  Win10 Powershell - v12.13.1, Win10 WSL Ubunutu v8.10.0
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows):  Win10 Powershell, Win10 WSL Ubunutu

**Comment by imthenachoman** [comment] 2019-12-07 03:39
I too am having this problem. 

@swvajanyatek Are you able to run `clasp apis list` or `clasp list` without errors? See #719.

**Comment by swvajanyatek** [comment] 2019-12-07 18:05
`clasp apis list` - prompts for a 'GCP projectId'
`clasp list` - returns the list of files, but never returns to the prompt

**Comment by imthenachoman** [comment] 2019-12-08 03:42
Yeah. Must be a bug. Now hopefully the devs see it.

**Comment by PopGoesTheWza** [comment] 2019-12-09 10:50
@imthenachoman are you also experiencing this issue on a Windows platform? Please detail your environment.

**Comment by imthenachoman** [comment] 2019-12-09 10:53
@PopGoesTheWza 

Yes

- Node version: **v10.16.3**
- Clasp version: **2.3.0**
- OS: **Windows 10**
- Enterprise G-Suite

**Comment by PopGoesTheWza** [comment] 2019-12-09 11:13
I personally have no Windows environment to attempt reproducing the issue.

**Comment by imthenachoman** [comment] 2019-12-09 11:14
@PopGoesTheWza Is there anything I can do to help debug? Is there some command we can run to increase verbosity to see what it’s trying to do?

**Comment by PopGoesTheWza** [comment] 2019-12-09 11:23
We can try opening a PR with Travis CI scope extended to test Windows platform...

**Comment by imthenachoman** [comment] 2019-12-16 16:09
I am not sure what that means. Is there anything I can do to get that done? The delay in returning to the prompt is a real productivity killer. :(

**Comment by PopGoesTheWza** [comment] 2019-12-16 21:57
@imthenachoman can you test the following:
1. uninstall `clasp`both locally and globally
2. invoke `clasp` via npx (i.e. `npx clasp apis list`)

**Comment by PopGoesTheWza** [comment] 2019-12-16 22:02
From a quick review of the issue, it might be necessary that every clasp command explicitly terminates after execution with `process.exit()`
Also try.. catch... for failing promises/async functions is lacking in some places.

**Comment by PopGoesTheWza** [comment] 2019-12-17 09:06
@swvajanyatek & @imthenachoman if you can try to build `clasp` from PR #721  (<https://github.com/PopGoesTheWza/clasp/tree/issue-717>) and test it... Travis currently fails because of exhausted quotas, thus requiring to wait 24 hours to run again.
Since I do not have a Windows system to use, I cannot test it myself.

**Comment by imthenachoman** [comment] 2019-12-17 16:15
> @imthenachoman can you test the following:
> 
> 1. uninstall `clasp`both locally and globally
> 2. invoke `clasp` via npx (i.e. `npx clasp apis list`)

1. `npm uninstall -g @google/clasp` and `npm uninstall @google/clasp`
2. `npx clasp clone ....`
    > (long wait, almost a minute)
    > { Error: Command failed: clasp -v
    > 'clasp' is not recognized as an internal or external command,
    > operable program or batch file.
    > 
    >     at ChildProcess.exithandler (child_process.js:294:12)
    >     at ChildProcess.emit (events.js:198:13)
    >     at maybeClose (internal/child_process.js:982:16)
    >     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) killed: false, code: 1, signal: null, cmd: 'clasp -v' }
    > Warning: files in subfolder are not accounted for unless you set a '.claspignore' file.
    > Cloned 10 files.
    > └─ main.js
    > └─ appsscript.json
    > Not ignored files:
    > └─ appsscript.json
    > └─ main.js
    > 
    > Ignored files:
    > └─ .clasp.json
    > (long wait, almost a minute)

> From a quick review of the issue, it might be necessary that every clasp command explicitly terminates after execution with `process.exit()`
> Also try.. catch... for failing promises/async functions is lacking in some places.

Do I need to do anything here? Not sure where/how I would add `process.exit()`?

> @swvajanyatek & @imthenachoman if you can try to build `clasp` from PR #721 (https://github.com/PopGoesTheWza/clasp/tree/issue-717) and test it... Travis currently fails because of exhausted quotas, thus requiring to wait 24 hours to run again.
> Since I do not have a Windows system to use, I cannot test it myself.

Uh, I will have to see how build `clasp`. I have never done that before. Any documentation/information on how to build `clasp`?

**Comment by imthenachoman** [comment] 2019-12-17 18:34
> @swvajanyatek & @imthenachoman if you can try to build `clasp` from PR #721 (https://github.com/PopGoesTheWza/clasp/tree/issue-717) and test it... Travis currently fails because of exhausted quotas, thus requiring to wait 24 hours to run again.
> Since I do not have a Windows system to use, I cannot test it myself.

I now realize Travis CI is a product name. I thought it was a person's name. 

I followed the instructions at https://github.com/google/clasp/blob/master/docs/develop.md:

- `tsc: npm install -g typescript`
- `npm uninstall -g @google/clasp`
- `npm install`
- `npm run build;`

Then, in the same directory, I ran `clasp clone ....`. It cloned the project fine but, after it was done, it still sat at the prompt for a bit.

**Comment by PopGoesTheWza** [comment] 2019-12-17 20:41
@imthenachoman develop.md is quite outdated it seems... :)

did you test with a copy of this branch? : https://github.com/PopGoesTheWza/clasp/tree/issue-717

**Comment by imthenachoman** [comment] 2019-12-17 21:21
> @imthenachoman develop.md is quite outdated it seems... :)

Did I do something wrong?

> did you test with a copy of this branch? : https://github.com/PopGoesTheWza/clasp/tree/issue-717

Yes. I downloaded a ZIP from that URL and then extracted locally. Can't `git clone` for various reasons.

**Comment by PopGoesTheWza** [comment] 2019-12-18 09:48
Odd. I bumped the PR to check that Travis CI now completes with node 8, 10 and 12 on Linux, MacOS and Windows.

Can you try and:
- download again from https://github.com/PopGoesTheWza/clasp/tree/issue-717
- check in `package.json` that `version` is `2.3.717`
- re-install with the commands `npm uninstall -g clasp`, `npm install` and `npm run build`

Test and report for as many clasp commands as possible (status, login, etc.)

TIA

**Comment by imthenachoman** [comment] 2019-12-18 15:08
Here is what I did:

1. downloaded https://github.com/PopGoesTheWza/clasp/archive/issue-717.zip
2. extracted
3. confirmed `package.json` shows `"version": "2.3.717"`
4. `npm uninstall -g clasp`
    > ```
    > up to date in 0.039s
    > ```
6. `npm uninstall -g @google/clasp`
    > ```
    > up to date in 0.037s
    > ```
7. `npm install`
    > ```
    > [...]
    > added 461 packages from 836 contributors in 14.917s
    > ```
8. `npm run build`
    > ```
    > 
    > > @google/clasp@2.3.717 build C:\Users\userid\Documents\VBG PS\clasp\clasp-issue-717
    > > npm run build-local && npm i -g --loglevel=error
    > 
    > 
    > > @google/clasp@2.3.717 build-local C:\Users\userid\Documents\VBG PS\clasp\clasp-issue-717
    > > tsc --project tsconfig.json
    > 
    > C:\Users\userid\AppData\Roaming\npm\clasp -> C:\Users\userid\AppData\Roaming\npm\node_modules\@google\clasp\src\index.js
    > + @google/clasp@2.3.717
    > added 1 package from 1 contributor in 0.93s
    > ```
9. renamed `~/.clasprc.json` to `~/.clasprc.jsonx`
10. `clasp login` -> opens a Chrome window with an error:
    > ```
    > 400. That’s an error.
    > 
    > Error: invalid_request
    > 
    > Invalid parameter value for redirect_uri: Missing scheme: http%3A%2F%2Flocalhost%3A54620
    > 
    > Learn more
    > 
    > Request Details
    >   access_type=offline
    >   scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fscript.deployments%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fscript.projects%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fscript.webapp.deploy%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.metadata.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fservice.management%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Flogging.read%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform
    >   response_type=code
    >   client_id=[redacted].apps.googleusercontent.com
    >   redirect_uri=http%3A%2F%2Flocalhost%3A54620
    > 
    > That’s all we know.
    > ```
11. `clasp login --no-localhost` worked but sat at prompt for a while
12. `clasp clone ....` worked but sat at prompt for a while

Do you need me to run more commands? Is there anyway to get more verbose debug output? And/or if you can tell me where to look in the code, maybe I can add dummy marker output (i.e. `1`, `2`, `3`, etc...) so I can see exactly at what step its getting "stuck" at?

Also, should I do `npm uninstall clasp` and `npm uninstall @google/clasp` in the same folder too?

**Comment by PopGoesTheWza** [comment] 2020-01-02 09:15
@imthenachoman 
step 4: `npm uninstall -g clasp` should be unnecessary (step 5 is correct)

steps 10 & 11: "worked but sat at prompt for a while" do you mean that it eventually returned correctly to the prompt? If so, this would mean that PR #721 fixes the issue. FYI, on MacOS too `@google/clasp` sometimes takes some times before returning to the prompt.

**Comment by imthenachoman** [comment] 2020-01-02 15:19
> steps 10 & 11: "worked but sat at prompt for a while" do you mean that it eventually returned correctly to the prompt? If so, this would mean that PR #721 fixes the issue. FYI, on MacOS too `@google/clasp` sometimes takes some times before returning to the prompt.

For me, it always eventually returned -- even before PR #721. I run the clasp command, like `clasp push`, it does its thing, and then, from what I can tell, just sits there waiting (or doing something in the background) before the process gracefully finishes. 

And, while it is waiting, the actual command finished. For example, if I type `clasp push`, it'll push the files and then wait. While it is waiting, before it gracefully finishes, I checked and the code was updated. So I'm not sure what it is doing after it finishes the push but before finishing.

**Comment by PopGoesTheWza** [comment] 2020-01-20 17:59
@imthenachoman can you try to build the current `master` branch from this repository? I committed some changes which should have node to exit in a more cleaner and graceful manner on windows.

**Comment by imthenachoman** [comment] 2020-01-21 20:36
No dice. It's still sits at the end...

**Comment by plonibarploni** [comment] 2020-05-14 16:30
I am having a similar issue, just instead of hanging indefinitely, it hangs for about a minute or two.

I'm running Ubuntu MATE 20.04 with `node` version v10.19.0 and `clasp` version 2.3.0.

**Comment by PopGoesTheWza** [comment] 2020-05-26 07:55
Can you try by building from PR #778 if there is any improvement?

**Comment by PopGoesTheWza** [comment] 2020-07-15 19:09
Can you test with the #791 unofficial release?

```shell
npm uninstall -g @google/clasp && npm install -g forked-clasp
clasp --version
# should be 2.4.0 or more
```

**Comment by plonibarploni** [comment] 2020-07-15 23:25
> Can you test with the #791 unofficial release?

I just tested it - there's no change in regard to this issue. However, it feels slower to perform any command.
It also ignores all files by default, which is not the current behavior.

**Comment by vinusv** [comment] 2020-08-20 05:21
While I have not looked at the latest unofficial release, I can confirm the behavior observed.
Time output is as follows:
```
real	1m22.860s
user	0m1.031s
sys	0m0.247s
```
Running Mac with `node v13.11.0` and `clasp 2.3.0`

**Comment by imthenachoman** [comment] 2020-09-17 22:16
Just checking on this. Is there anything we can do to help debug. Is there a way I can see on what line in the code-base clasp is getting hung at?

**Comment by plonibarploni** [comment] 2020-10-07 20:28
I haven't been using `clasp` or Google Apps Script for a while, but I just had to come back to an old project and (without updating `node` or `clasp`) it now returns to the prompt immediately, without hanging.

**Comment by imthenachoman** [comment] 2020-10-07 21:54
@plonibarploni What version are they? I am still having issues and I am using the latest everything.

**Comment by plonibarploni** [comment] 2020-10-08 03:43
@imthenachoman I posted them [earlier](https://github.com/google/clasp/issues/717#issuecomment-628747248): `node` version v10.19.0 and `clasp` version 2.3.0.

**Comment by imthenachoman** [comment] 2021-01-29 02:46
There seem to be multiple issues for the same thing. I am sure there are more but I can't find all of them. Not sure which one we want to be primary so I am posting this in all of them. Any resolution or idea what is wrong?

- https://github.com/google/clasp/issues/805
- https://github.com/google/clasp/issues/717 (this one)
- https://github.com/google/clasp/issues/257

**Comment by PopGoesTheWza** [comment] 2021-03-19 20:28
Try replacing `@google/clasp` 2.3.0 with `forked-clasp` which is more advanced. This issue is fixed.

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```

**Comment by PopGoesTheWza** [comment] 2021-05-12 22:08
Fixed in https://github.com/google/clasp/releases/tag/v2.3.1

**Closed by PopGoesTheWza** 2021-05-12 22:08 UTC
