### ISSUE TITLE
Blob doesn't implement BlobSource interface method getBlob in TypeScript

### ISSUE THREAD

**Issue by jnovate** [google/clasp#267] opened 2018-07-27 16:48 UTC
## Expected Behavior
GoogleAppsScript.Base.Blob should have getBlob()

## Actual Behavior
It doesn't

## Steps to Reproduce the Problem
Utilities.gzip(Utilities.newBlob('text'))

## Specifications

  - Node version (`node -v`): v8.9.3
  - Version (`clasp -v`):1.5.0
  - OS (Mac/Linux/Windows): Mac

**Comment by grant** [comment] 2018-07-30 22:52
Can you provide an example using `getBlob`?

[`HTTPResponse.getBlob()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.url-fetch.d.ts#L20) exists:
https://developers.google.com/apps-script/reference/url-fetch/http-response#getBlob()

I don't think `blob.getBlob()` is valid Apps Script.

**Comment by grant** [comment] 2018-08-01 16:12
`Blob.getBlob` doesn't seem like a valid type in the docs, and this issue hasn't seen a reply, so I'm going to close this issue. Comment if you want me to re-open it.

**Closed by grant** 2018-08-01 16:12 UTC
Labels: TypeScript

**Comment by jnovate** [comment] 2018-08-02 07:08
With TS you get `Argument of type 'Blob' is not assignable to parameter of type 'BlobSource'. Property 'getBlob' is missing in type 'Blob'.`
when using for example Utilities.gzip(Utilities.newBlob('text')). Note that 'blob' in Utilities.gzip(blob) is a BlobSource and not Blob.

**Comment by comfortablynick** [comment] 2018-08-28 02:14
I get this same error when returning `UrlFetchApp.fetch().getBlob()` to `DriveApp.createFile()`. I can't figure out what I'm doing wrong.

**Comment by takei-shg** [comment] 2018-11-05 13:07
I also get the same error `Argument of type 'Blob' is not assignable to parameter of type 'BlobSource'. Property 'getBlob' is missing in type 'Blob'.` with below code.
```
// import Base = GoogleAppsScript.Base;
const fileBlob: Base.Blob = DriveApp.getFileById(fileId).getBlob();
const unzippedBlob: Base.Blob = Utilities.unzip(fileBlob)[0]; // Utilities.unzip cause type error.
```

I think the problem is the wrong function type of Utilities.unzip (and gzip, so on).
The function type is currently `unzip(blob: Base.BlobSource): Base.Blob[];`,
 but it should be `      unzip(blob: Base.Blob): Base.Blob[];`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.utilities.d.ts#L70
(Though JS version also set the type BlobSource instead of Blob. It would be wrong. https://developers.google.com/apps-script/reference/utilities/utilities#unzipblob)

**Comment by grant** [comment] 2018-11-05 16:22
Please file a pull request on DefinitelyTyped to fix this issue.
