### ISSUE TITLE
Switch a project version with clasp

### ISSUE THREAD

**Issue by kenchan0130** [google/clasp#525] opened 2019-02-08 09:53 UTC
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
`clasp deploy` would switch using a project version.

## Actual Behavior
`clasp deploy` creates a deployment and a project version without switch the project version.

If we deploy version 24, we cannot switch the version with clasp. 

**image 1**
<img width="165" alt="2019-02-08 18 49 23" src="https://user-images.githubusercontent.com/1155067/52470826-92f27300-2bd2-11e9-85e9-146b2669a459.png">

**image 2**
<img width="155" alt="2019-02-08 18 49 32" src="https://user-images.githubusercontent.com/1155067/52470783-722a1d80-2bd2-11e9-8680-1f5168b77fc1.png">

## Solution
* Use web UI.

**Comment by erickoledadevrel** [comment] 2019-02-08 15:45
I believe this is a duplicate of issue #63, and the investigation there concluded that this is due a missing feature or bug with the underlying Apps Script API.

**Closed by erickoledadevrel** 2019-02-08 15:45 UTC
