### ISSUE TITLE
'clasp version' command issuing TypeError

### ISSUE THREAD

**Issue by badgercoder17** [google/clasp#261] opened 2018-07-24 19:57 UTC
(Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.)

## Expected Behavior
Running the command 'clasp version [description]' should allow me to create a new version of my project successfully.

## Actual Behavior
Running the version command causes thisUnhandledPromiseRejectionWarning to appear:

`$ clasp version "head version"
/ Creating a new version...(node:252796) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined 
at
C:\Users\my_username\AppData\Roaming\npm\node_modules\@google\clasp\src\commands.js:654:3
at
C:\Users\my_username\AppData\Roaming\npm\node_modules\@google\clasp\node_modules\googleapis\build\src\lib\apirequest.js:88:42
at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:252796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:252796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/ Creating a new version...`

It then hangs indefinitely while saying it is still creating a new version. Spinner will continue to spin.

## Steps to Reproduce the Problem
 Note: I tried these steps in both the Windows powershell and the Git Bash shell
  1. logged in using 'clasp login'
  2. 'clasp clone' my project, which worked successfully
  3. 'clasp version "first version"', which caused the error.

My account is part of my companies G Suite account, but I was able to provide permissions to access and modify my drive, so this shouldn't be causing any issues.

## Specifications

  - Node version (v8.11.3):
  - Version (1.5.0):
  - OS (Windows 10):

**Comment by campionfellin** [comment] 2018-07-26 03:52
Hey @badgercoder17 , I was unable to reproduce this error, but I believe this is where it stems from:

https://github.com/google/clasp/blob/0a7ac1366acfb8db91a9600fad9cee675ecce535/src/commands.ts#L477

It is trying to unwrap the `data` from the response, but with an undefined response, it throws the `UnhandledPromiseRejectionWarning`.

Unsure of the root cause of your issue, but changing this to something like:

```
  }, {}, (error: any, res: any) => {
    spinner.stop(true);
    if (error) {
      logError(error);
    } else {
      const data = res.data;
      console.log(LOG.VERSION_CREATED(data.versionNumber));
    }
```

should at least get the spinner to stop and then hit `logError(...)` of whatever the true error is.

I can go ahead and take a look at it this weekend for you.

**Comment by grant** [comment] 2018-07-26 19:01
We should remove all destructured API responses (`{ data }`) due to possible errors in the API request.

**Comment by campionfellin** [comment] 2018-08-02 04:25
@grant was this done in https://github.com/google/clasp/commit/c51683d46e0c33ba745c3b22a1815a02331082ee?

If so then, should we close this?

**Comment by grant** [comment] 2018-08-02 04:45
Yup! Closing.

**Closed by grant** 2018-08-02 04:45 UTC
