### ISSUE TITLE
Clasp Login requiring package.json

### ISSUE THREAD

**Issue by myxxmikeyxx** [google/clasp#860] opened 2021-07-19 12:27 UTC
> (Note: Non-breaking issues are likely not to be prioritized. Please consider a PR in addition to your issue)
This only happened since I updated my clasp, the version I had before was probably about two years old. I know before I updated clasp it worked fine and did not require the package.json.

## Expected Behavior
In an empty directory or location to be able to just do clasp login so I can copy a script that I have already made online to my pc to work in it locally.

## Actual Behavior
Requires ```npm init``` to be ran before to create a package.json before being able to login to clasp.
Note: When trying to get clasp version it also will not let you do that unless the folder has a package.json file.

## Steps to Reproduce the Problem

1. Install node.js
2. npm install @google/clasp -g
3. create empty folder and open terminal in empty folder
4. clasp login

## Specifications

- Node version (`node -v`): v14.17.3
- Version (`clasp -v`):2.4.0
- OS (Mac/Linux/Windows):Windows 10, 64bit

**Comment by juliankleine** [comment] 2021-08-03 10:23
Two weeks and no reaction, currently the version is broken - please prioritize

Workaroung

```
npm i @google/clasp@2.3 -g
```

**Comment by sqrrrl** [comment] 2021-08-03 18:46
Closing as duplicate of #856

**Closed by sqrrrl** 2021-08-03 18:46 UTC
